# Generated by Django 3.0.2 on 2020-01-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
